#!/usr/bin/env bash
# ThreatPulse Deployment Script
# Deploys frontend to Vercel, backend to Railway, database on Supabase

set -e

echo "========================================="
echo "ThreatPulse Deployment Setup"
echo "========================================="
echo ""
echo "This script guides you through deploying ThreatPulse."
echo "You will need accounts on: GitHub, Vercel, Railway, Supabase, Stripe, Resend, Anthropic"
echo ""

# ── Step 1: Database (Supabase) ──
echo "STEP 1: DATABASE"
echo "1. Go to supabase.com and create a free account"
echo "2. Click 'New Project', name it 'threatpulse'"
echo "3. Copy the connection string from Settings > Database > Connection String (URI)"
echo "4. It looks like: postgresql://postgres:PASSWORD@db.xxxx.supabase.co:5432/postgres"
echo "5. Paste it into your .env file as DATABASE_URL"
echo ""

# ── Step 2: API Keys ──
echo "STEP 2: API KEYS"
echo "Get these keys and add them to your .env file:"
echo ""
echo "  ANTHROPIC_API_KEY"
echo "    -> console.anthropic.com > API Keys > Create Key"
echo "    -> Set a spend limit of \$10/month to start"
echo ""
echo "  STRIPE_SECRET_KEY + STRIPE_WEBHOOK_SECRET"
echo "    -> dashboard.stripe.com > Developers > API Keys"
echo "    -> Create two Products: 'Professional' at \$39/mo and 'Enterprise' at \$199/mo"
echo "    -> Copy each Product's Price ID into STRIPE_PRICE_PRO and STRIPE_PRICE_ENTERPRISE"
echo "    -> Webhook secret comes after you set up the webhook endpoint (Step 4)"
echo ""
echo "  RESEND_API_KEY"
echo "    -> resend.com > API Keys > Create Key"
echo "    -> Verify your sending domain in Resend's dashboard"
echo ""
echo "  JWT_SECRET"
echo "    -> Generate with: openssl rand -hex 32"
echo ""

# ── Step 3: Deploy Backend to Railway ──
echo "STEP 3: BACKEND DEPLOYMENT (Railway)"
echo "1. Go to railway.app and sign in with GitHub"
echo "2. Click 'New Project' > 'Deploy from GitHub Repo'"
echo "3. Select your threatpulse repo"
echo "4. Railway will ask which directory: select 'backend'"
echo "5. Go to Settings > Environment and add all your .env variables"
echo "6. Railway auto-detects the Dockerfile and builds"
echo "7. Go to Settings > Networking > Generate Domain"
echo "8. Copy the URL (like threatpulse-backend.up.railway.app)"
echo "9. Run the database migration:"
echo "   railway run alembic upgrade head"
echo "10. Seed initial data:"
echo "    railway run python -m app.scrapers.run --seed"
echo ""

# ── Step 4: Configure Stripe Webhook ──
echo "STEP 4: STRIPE WEBHOOK"
echo "1. Go to dashboard.stripe.com > Developers > Webhooks"
echo "2. Click 'Add Endpoint'"
echo "3. URL: https://YOUR-RAILWAY-URL/api/webhook/stripe"
echo "4. Select events: checkout.session.completed, customer.subscription.updated, customer.subscription.deleted"
echo "5. Copy the Webhook Signing Secret into STRIPE_WEBHOOK_SECRET in Railway's env vars"
echo ""

# ── Step 5: Deploy Frontend to Vercel ──
echo "STEP 5: FRONTEND DEPLOYMENT (Vercel)"
echo "1. Go to vercel.com and sign in with GitHub"
echo "2. Click 'Add New Project' > Import your threatpulse repo"
echo "3. Set Root Directory to 'frontend'"
echo "4. Framework Preset: Next.js"
echo "5. Add Environment Variables:"
echo "   NEXT_PUBLIC_API_URL = https://YOUR-RAILWAY-URL"
echo "   NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = pk_live_xxxx (from Stripe dashboard)"
echo "6. Click Deploy"
echo "7. Your site is live at threatpulse.vercel.app"
echo ""

# ── Step 6: Custom Domain ──
echo "STEP 6: CUSTOM DOMAIN (Optional)"
echo "1. In Vercel: Settings > Domains > Add your domain"
echo "2. Add the DNS records Vercel gives you at your domain registrar"
echo "3. Update CORS in backend/app/main.py to include your domain"
echo "4. Update success_url/cancel_url in backend/app/api/routes.py"
echo ""

# ── Step 7: Start the Scraper ──
echo "STEP 7: SCRAPER"
echo "Option A: Run as a separate Railway service"
echo "  - Create a new service in the same Railway project"
echo "  - Set the same env vars"
echo "  - Override the start command: python -m app.scrapers.run --watch"
echo ""
echo "Option B: Use Railway cron jobs"
echo "  - railway cron add '0 * * * *' 'python -m app.scrapers.run'"
echo ""

echo "========================================="
echo "ESTIMATED MONTHLY COSTS"
echo "========================================="
echo "Supabase (free tier):     \$0"
echo "Railway (Hobby):          \$5"
echo "Vercel (Hobby):           \$0"
echo "Anthropic API:            \$5-20 (depends on scrape volume)"
echo "Resend (free tier):       \$0 (up to 3000 emails/month)"
echo "Stripe:                   2.9% + \$0.30 per transaction"
echo "Domain:                   \$10-15/year"
echo "-----------------------------------------"
echo "TOTAL:                    ~\$10-25/month before revenue"
echo "========================================="
